Repository gfoidl/Base64, pull requests merged in 2018-12, with the labels that each got.

#28 Code Coverage scripts, CI, README.md
  .azure/pipelines/jobs/build_and_test.yml
  README.md
  build.sh
Labels: ci-pipeline

#24 Exposes the method IBase64 GetDecodedLength with an int as parameter.
  source/gfoidl.Base64/Base64.cs
  source/gfoidl.Base64/IBase64.cs
  source/gfoidl.Base64/Internal/Base64Encoder/Base64Encoder.Decode.cs
  source/gfoidl.Base64/Internal/Base64UrlEncoder/Base64UrlEncoder.Decode.cs
  tests/gfoidl.Base64.Tests/Internal/Base64EncoderTests/GetDecodedLength.cs
  tests/gfoidl.Base64.Tests/Internal/Base64UrlEncoderTests/GetDecodedLength.cs
Labels: enhancement

#38 Added detection for base64 or base64Url
  demo/gfoidl.Base64.Demo/Program.cs
  source/gfoidl.Base64/Base64.cs
  source/gfoidl.Base64/EncodingType.cs
  tests/gfoidl.Base64.Tests/Base64Tests/Default.cs
  tests/gfoidl.Base64.Tests/Base64Tests/DetectEncoding.cs
  tests/gfoidl.Base64.Tests/Base64Tests/DetectEncoding_T.cs
  tests/gfoidl.Base64.Tests/Base64Tests/Url.cs
Labels: enhancement

#43 Documented exceptions in xml comments
  source/gfoidl.Base64/Base64.cs
  source/gfoidl.Base64/IBase64.cs
  source/gfoidl.Base64/Internal/Base64EncoderImpl.cs
Labels: documentation

#46 React to HW-api changes
  .azure/pipelines/ci.yml
  .azure/pipelines/jobs/build_and_test.yml
  global.json
  source/gfoidl.Base64/Internal/Avx2Helper.cs
  source/gfoidl.Base64/Internal/Base64Encoder/Base64Encoder.Decode.cs
  source/gfoidl.Base64/Internal/Base64Encoder/Base64Encoder.Encode.cs
  source/gfoidl.Base64/Internal/Base64Encoder/Base64Encoder.cs
  source/gfoidl.Base64/Internal/Base64EncoderImpl.cs
  source/gfoidl.Base64/Internal/Base64UrlEncoder/Base64UrlEncoder.Decode.cs
  source/gfoidl.Base64/Internal/Base64UrlEncoder/Base64UrlEncoder.Encode.cs
  source/gfoidl.Base64/Internal/Base64UrlEncoder/Base64UrlEncoder.cs
  tests/gfoidl.Base64.Tests/Internal/Avx2HelperTests/LessThan.cs
  tests/gfoidl.Base64.Tests/Internal/Base64EncoderTests/GetDecodedLength.cs
  tests/gfoidl.Base64.Tests/Internal/Base64EncoderTests/GetMaxDecodedLength.cs
Labels: simd

#50 Added note for .NET Core 2.2 to ReadMe
  README.md
Labels: simd

#52 Vector*Helper for cleaner code
  perf/gfoidl.Base64.Benchmarks/Vector128HelperBenchmarks/ReadVector128Char.cs
  perf/gfoidl.Base64.Benchmarks/Vector128HelperBenchmarks/WriteVector128Char.cs
  perf/gfoidl.Base64.Benchmarks/Vector256HelperBenchmarks/ReadVector256Byte.cs
  perf/gfoidl.Base64.Benchmarks/Vector256HelperBenchmarks/ReadVector256Char.cs
  perf/gfoidl.Base64.Benchmarks/Vector256HelperBenchmarks/WriteVector256Byte.cs
  perf/gfoidl.Base64.Benchmarks/Vector256HelperBenchmarks/WriteVector256Char.cs
  perf/gfoidl.Base64.Benchmarks/results/Vector128HelperBenchmarks/ReadVector128Char-report.csv
  perf/gfoidl.Base64.Benchmarks/results/Vector128HelperBenchmarks/ReadVector128Char-report.md
  perf/gfoidl.Base64.Benchmarks/results/Vector128HelperBenchmarks/WriteVector128Char-report.csv
  perf/gfoidl.Base64.Benchmarks/results/Vector128HelperBenchmarks/WriteVector128Char-report.md
  perf/gfoidl.Base64.Benchmarks/results/Vector256HelperBenchmarks/ReadVector256Byte-report.csv
  perf/gfoidl.Base64.Benchmarks/results/Vector256HelperBenchmarks/ReadVector256Byte-report.md
  perf/gfoidl.Base64.Benchmarks/results/Vector256HelperBenchmarks/ReadVector256Char-report.csv
  perf/gfoidl.Base64.Benchmarks/results/Vector256HelperBenchmarks/ReadVector256Char-report.md
  perf/gfoidl.Base64.Benchmarks/results/Vector256HelperBenchmarks/WriteVector256Byte-report.csv
  perf/gfoidl.Base64.Benchmarks/results/Vector256HelperBenchmarks/WriteVector256Byte-report.md
  perf/gfoidl.Base64.Benchmarks/results/Vector256HelperBenchmarks/WriteVector256Char-report.csv
  perf/gfoidl.Base64.Benchmarks/results/Vector256HelperBenchmarks/WriteVector256Char-report.md
  source/gfoidl.Base64/Internal/Avx2Helper.cs
  source/gfoidl.Base64/Internal/Base64Encoder/Base64Encoder.Decode.cs
  source/gfoidl.Base64/Internal/Base64Encoder/Base64Encoder.Decode.netcoreapp2.1.cs
  source/gfoidl.Base64/Internal/Base64Encoder/Base64Encoder.Decode.netcoreapp3.0.cs
  source/gfoidl.Base64/Internal/Base64Encoder/Base64Encoder.Encode.cs
  source/gfoidl.Base64/Internal/Base64Encoder/Base64Encoder.Encode.netcoreapp2.1.cs
  source/gfoidl.Base64/Internal/Base64Encoder/Base64Encoder.Encode.netcoreapp3.0.cs
  source/gfoidl.Base64/Internal/Base64UrlEncoder/Base64UrlEncoder.Decode.cs
  source/gfoidl.Base64/Internal/Base64UrlEncoder/Base64UrlEncoder.Decode.netcoreapp2.1.cs
  source/gfoidl.Base64/Internal/Base64UrlEncoder/Base64UrlEncoder.Decode.netcoreapp3.0.cs
  source/gfoidl.Base64/Internal/Base64UrlEncoder/Base64UrlEncoder.Encode.cs
  source/gfoidl.Base64/Internal/Base64UrlEncoder/Base64UrlEncoder.Encode.netcoreapp2.1.cs
  source/gfoidl.Base64/Internal/Base64UrlEncoder/Base64UrlEncoder.Encode.netcoreapp3.0.cs
  source/gfoidl.Base64/Internal/Vector128Helper.cs
  source/gfoidl.Base64/Internal/Vector256Helper.cs
  source/gfoidl.Base64/gfoidl.Base64.csproj
  tests/gfoidl.Base64.Tests/Internal/Avx2HelperTests/Read.cs
  tests/gfoidl.Base64.Tests/Internal/Avx2HelperTests/Write.cs
  tests/gfoidl.Base64.Tests/Internal/Vector128HelperTests/ReadVector128.cs
  tests/gfoidl.Base64.Tests/Internal/Vector128HelperTests/WriteVector128.cs
  tests/gfoidl.Base64.Tests/Internal/Vector256HelperTests/LessThan.cs
  tests/gfoidl.Base64.Tests/Internal/Vector256HelperTests/ReadVector256.cs
  tests/gfoidl.Base64.Tests/Internal/Vector256HelperTests/WriteVector256.cs
  tests/gfoidl.Base64.Tests/gfoidl.Base64.Tests.csproj
Labels: perf, simd

#53 Reverted MacOS-hack / skip for AVX2
  source/gfoidl.Base64/Internal/Base64Encoder/Base64Encoder.Decode.netcoreapp3.0.cs
  source/gfoidl.Base64/Internal/Base64Encoder/Base64Encoder.Encode.netcoreapp3.0.cs
  source/gfoidl.Base64/Internal/Base64EncoderImpl.netcoreapp3.0.cs
  source/gfoidl.Base64/Internal/Base64UrlEncoder/Base64UrlEncoder.Decode.netcoreapp3.0.cs
  source/gfoidl.Base64/Internal/Base64UrlEncoder/Base64UrlEncoder.Encode.netcoreapp3.0.cs
  tests/Directory.Build.props
  tests/gfoidl.Base64.Tests/HWInfo.cs
  tests/gfoidl.Base64.Tests/Internal/Base64EncoderTests/Decode.cs
  tests/gfoidl.Base64.Tests/Internal/Base64UrlEncoderTests/Decode.cs
  tests/gfoidl.Base64.Tests/Internal/Vector256HelperTests/LessThan.cs
  tests/gfoidl.Base64.Tests/Internal/Vector256HelperTests/ReadVector256.cs
  tests/gfoidl.Base64.Tests/Internal/Vector256HelperTests/WriteVector256.cs
  tests/gfoidl.Base64.Tests/gfoidl.Base64.Tests.csproj
Labels: simd
