Repository gfoidl/Base64, pull requests merged in 2020-03, with the labels that each got.

#114 Minor improvement on the `dataLength % 3`.
  source/gfoidl.Base64/Internal/Base64UrlEncoder/Base64UrlEncoder.Encode.cs
Labels: perf

#119 Update MacOS image to macOS-10.15
  .azure/pipelines/ci.yml
Labels: ci-pipeline

#115 Introduces `TryGetDataLength` in addition to `GetDataLen`.
  source/gfoidl.Base64/Internal/Base64UrlEncoder/Base64UrlEncoder.Decode.cs
  source/gfoidl.Base64/Internal/Base64UrlEncoder/Base64UrlEncoder.Decode.netcoreapp.cs
  source/gfoidl.Base64/Internal/Base64UrlEncoder/Base64UrlEncoder.Decode.netstandard.cs
Labels: enhancement

#123 Fixes some naming rule violations
  source/gfoidl.Base64/Internal/Base64Encoder/Base64Encoder.Decode.netcoreapp.cs
  source/gfoidl.Base64/Internal/Base64Encoder/Base64Encoder.Encode.netcoreapp.cs
  source/gfoidl.Base64/Internal/Base64EncoderImpl.avx.cs
  source/gfoidl.Base64/Internal/Base64UrlEncoder/Base64UrlEncoder.Decode.netcoreapp.cs
  source/gfoidl.Base64/Internal/Base64UrlEncoder/Base64UrlEncoder.Encode.netcoreapp.cs
Labels: code-quality / tests

#127 Use uint for division instead of int
  source/gfoidl.Base64/Internal/Base64Encoder/Base64Encoder.Decode.netcoreapp.cs
  source/gfoidl.Base64/Internal/Base64Encoder/Base64Encoder.Decode.netstandard.cs
  source/gfoidl.Base64/Internal/Base64EncoderImpl.cs
  source/gfoidl.Base64/Internal/Base64UrlEncoder/Base64UrlEncoder.Decode.netcoreapp.cs
  source/gfoidl.Base64/Internal/Base64UrlEncoder/Base64UrlEncoder.Decode.netstandard.cs
Labels: code-quality / tests, perf

#124 Reuse vectors
  source/gfoidl.Base64/Internal/Base64Encoder/Base64Encoder.Decode.netcoreapp.cs
  source/gfoidl.Base64/Internal/Base64Encoder/Base64Encoder.Encode.netcoreapp.cs
  source/gfoidl.Base64/Internal/Base64UrlEncoder/Base64UrlEncoder.Decode.netcoreapp.cs
  source/gfoidl.Base64/Internal/Base64UrlEncoder/Base64UrlEncoder.Encode.netcoreapp.cs
  tests/gfoidl.Base64.Tests/Internal/Base64EncoderTests/Roundtrips.cs
Labels: perf, simd

#130 Get code coverage on "intrinsic-build"
  .azure/pipelines/jobs/build_and_test_intrinsics.yml
Labels: code-quality / tests

#131 ReadMe shows MyGet with prereleases
  ReadMe.md
Labels: documentation

#132 Run more benchmarks in CI
  perf/gfoidl.Base64.Benchmarks/DecodeStringUrlBenchmark.cs
  perf/gfoidl.Base64.Benchmarks/results/DecodeStringUrlBenchmark-report.csv
  perf/gfoidl.Base64.Benchmarks/results/DecodeStringUrlBenchmark-report.md
  perf/gfoidl.Base64.Benchmarks/results/EncodeStringUrlBenchmark-report.csv
  perf/gfoidl.Base64.Benchmarks/results/EncodeStringUrlBenchmark-report.md
  run-benchmarks.sh
Labels: ci-pipeline

#134 Benchmarks with HW-config and Memorydiagnoser
  perf/gfoidl.Base64.Benchmarks/Base64EncoderBenchmark.cs
  perf/gfoidl.Base64.Benchmarks/Base64UrlEncoderBenchmark.cs
  perf/gfoidl.Base64.Benchmarks/BaseBenchmark.cs
  perf/gfoidl.Base64.Benchmarks/DecodeStringUrlBenchmark.cs
  perf/gfoidl.Base64.Benchmarks/DecodeUtf8Benchmark.cs
  perf/gfoidl.Base64.Benchmarks/EncodeStringUrlBenchmark.cs
  perf/gfoidl.Base64.Benchmarks/EncodeUtf8Benchmark.cs
  perf/gfoidl.Base64.Benchmarks/ReadOnlySequenceBenchmark.cs
  perf/gfoidl.Base64.Benchmarks/results/DecodeStringUrlBenchmark-report.csv
  perf/gfoidl.Base64.Benchmarks/results/DecodeStringUrlBenchmark-report.md
  perf/gfoidl.Base64.Benchmarks/results/EncodeStringUrlBenchmark-report.csv
  perf/gfoidl.Base64.Benchmarks/results/EncodeStringUrlBenchmark-report.md
Labels: benchmarks

#138 Fixed broken links in ReadMe.md
  ReadMe.md
Labels: documentation

#142 Added GH-action for auto-merging
  .github/workflows/auto-merge.yml
  gfoidl.Base64.sln
Labels: ci-pipeline

#141 Fix for MAC-benchmark problem
  run-benchmarks.sh
Labels: automerge, benchmarks

#144 Automerge bot / GH-action
  .github/pull_request_template.md
  .github/workflows/auto-merge.yml
  .github/workflows/automerge.yml
  gfoidl.Base64.sln
Labels: ci-pipeline

#146 Removed some xml-doc-comments by <inheritdoc>
  source/gfoidl.Base64/Base64.cs
Labels: automerge, documentation

#148 Documented bad performance for .NET Full
  perf/gfoidl.Base64.Benchmarks/results/net461/EncodeStringBenchmark-report.csv
  perf/gfoidl.Base64.Benchmarks/results/net461/EncodeStringBenchmark-report.md
  perf/gfoidl.Base64.Benchmarks/results/net461/EncodeStringUrlBenchmark-report.csv
  perf/gfoidl.Base64.Benchmarks/results/net461/EncodeStringUrlBenchmark-report.md
  perf/gfoidl.Base64.Benchmarks/results/netcoreapp3.0/EncodeStringBenchmark-report.csv
  perf/gfoidl.Base64.Benchmarks/results/netcoreapp3.0/EncodeStringBenchmark-report.md
  source/gfoidl.Base64/IBase64.cs
  source/gfoidl.Base64/Internal/Base64Encoder/Base64Encoder.Encode.cs
  source/gfoidl.Base64/gfoidl.Base64.csproj
Labels: automerge, documentation, perf, tfm-netstandard

#149 docfx api-doc
  Directory.Build.props
  api-doc/.gitignore
  api-doc/api/.gitignore
  api-doc/api/index.md
  api-doc/articles/benchmarks.md
  api-doc/articles/intro.md
  api-doc/articles/toc.yml
  api-doc/docfx.json
  api-doc/filterConfig.yml
  api-doc/images/logo_32.png
  api-doc/index.md
  api-doc/toc.yml
Labels: documentation

#150 CI for api-doc
  .azure/pipelines/ci.yml
  .azure/pipelines/jobs/api-doc.yml
  gfoidl.Base64.sln
Labels: automerge, ci-pipeline, documentation

#152 DevOps pipeline: splitted into stages
  .azure/pipelines/ci.yml
  .azure/pipelines/fuzz.yml
  .azure/pipelines/jobs/api-doc.yml
  .azure/pipelines/jobs/benchmarks.yml
  .azure/pipelines/jobs/benchmarks_net_full.yml
  .azure/pipelines/jobs/build_and_test.yml
  .azure/pipelines/jobs/build_and_test_intrinsics.yml
  .azure/pipelines/jobs/build_docs.yml
  .azure/pipelines/jobs/demo.yml
  .azure/pipelines/jobs/deploy_docs.yml
  .azure/pipelines/jobs/deploy_nuget.yml
  .azure/pipelines/jobs/fuzzing.yml
  gfoidl.Base64.sln
Labels: ci-pipeline
